title: ICT-beveiliging
description: >- # this means to ignore newlines until "baseurl:"
  Website met oefenbestanden, werkbladen en tools voor ICT-beveiliging.
github_username:  botris

# Build settings
theme: jekyll-theme-minimal

show_downloads: false

collections:
  hoofdstukken:
    output: true

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from